version: "3.9"

services:
  web:
    environment:
      VIRTUAL_HOST: "simulator.pylabrobot.org"
      LETSENCRYPT_HOST: "simulator.pylabrobot.org"
      USE_IP_HASH: 1 # doesn't work yet, so just use one replica

      FLASK_ENV: "production"
      PRODUCTION: "1"
    ports: []
    entrypoint:
      [
        "gunicorn",
        "--workers",
        "1",
        "--threads",
        "10",
        "--bind",
        ":5001",
        "wsgi:app",
        "--timeout",
        "90",
        "--worker-class",
        "gevent",
      ]

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  monitor:
    environment:
      PRODUCTION: "1"

  worker:
    environment:
      PRODUCTION: "1"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=rick@pylabrobot.org
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
