version: "3.9"

services:
  redis:
    platform: linux/amd64
    image: "redis:alpine"
    networks:
      - web
    expose:
      - 6379
    volumes:
      - cache:/data
    mem_reservation: 128m

  db:
    platform: linux/amd64
    image: "postgres:alpine"
    networks:
      - web
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "db"
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    mem_reservation: 128m
    secrets:
      - db_password

  web:
    platform: linux/amd64
    build: .
    depends_on:
      - redis
      - db
    expose:
      - "5001"
    networks:
      - web
      - nbs
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: "localhost"

      REDIS_HOST: "redis"
      DB_USER: "postgres"
      DB_HOST: "db"
      DB_NAME: "db"
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key

      PYTHONUNBUFFERED: 1
    secrets:
      - db_password
      - secret_key
    mem_reservation: 128m

  worker:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    mem_reservation: 64m
    secrets:
      - db_password
      - secret_key
    environment:
      REDIS_HOST: "redis"

      FLASK_ENV: "development"
      DB_USER: "postgres"
      DB_HOST: "db"
      DB_NAME: "db"
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key

      PYTHONUNBUFFERED: 1

  monitor:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    mem_reservation: 64m
    secrets:
      - db_password
      - secret_key
    restart: always
    environment:
      REDIS_HOST: "redis"

      FLASK_ENV: "development"
      DB_USER: "postgres"
      DB_HOST: "db"
      DB_NAME: "db"
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key

      PYTHONUNBUFFERED: 1

  nginx:
    platform: linux/amd64
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
    environment:
      - DEFAULT_HOST=web.local
    networks:
      - web
    mem_reservation: 128m

networks:
  web:
    driver: bridge
  nbs:
    driver: bridge
    internal: true

secrets:
  db_password:
    file: db_password.txt
  secret_key:
    file: secret_key.txt

volumes:
  db:
    driver: local
  cache:
    driver: local
