version: "3.9"

services:
  web:
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - "./:/app"
    environment:
      FLASK_ENV: "development"
    entrypoint: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
