CONTAINER_STARTED = "CONTAINER_STARTED"
CONTAINER_STOPPED = "CONTAINER_STOPPED"

NOTEBOOK_STARTED = "NOTEBOOK_STARTED"
NOTEBOOK_STOPPED = "NOTEBOOK_STOPPED"

SIMULATION_FILE_SERVER_STARTED = "SIMULATION_FILE_SERVER_STARTED"
SIMULATION_FILE_SERVER_STOPPED = "SIMULATION_FILE_SERVER_STOPPED"

CONTAINER_UPGRADE = "CONTAINER_UPGRADE"

CONTAINER_DESTROYED = "CONTAINER_DESTROYED"
